src/Entity/Idea.php
<?php

namespace App\Entity;

use App\Repository\IdeaRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: IdeaRepository::class)]
class Idea
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $idea_name = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $idea_created_at = null;

    #[ORM\ManyToOne(inversedBy: 'ideas')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Tag $idea_tag_id = null;

    #[ORM\ManyToOne(inversedBy: 'ideas')]
    #[ORM\JoinColumn(nullable: false)]
    private ?IdeaBox $idea_box_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdeaName(): ?string
    {
        return $this->idea_name;
    }

    public function setIdeaName(string $idea_name): static
    {
        $this->idea_name = $idea_name;

        return $this;
    }

    public function getIdeaCreatedAt(): ?\DateTimeImmutable
    {
        return $this->idea_created_at;
    }

    public function setIdeaCreatedAt(\DateTimeImmutable $idea_created_at): static
    {
        $this->idea_created_at = $idea_created_at;

        return $this;
    }

    public function getIdeaTagId(): ?Tag
    {
        return $this->idea_tag_id;
    }

    public function setIdeaTagId(?Tag $idea_tag_id): static
    {
        $this->idea_tag_id = $idea_tag_id;

        return $this;
    }

    public function getIdeaBoxId(): ?IdeaBox
    {
        return $this->idea_box_id;
    }

    public function setIdeaBoxId(?IdeaBox $idea_box_id): static
    {
        $this->idea_box_id = $idea_box_id;

        return $this;
    }
}

src/Entity/Tag.php
<?php

namespace App\Entity;

use App\Repository\TagRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TagRepository::class)]
class Tag
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $tag_name = null;

    #[ORM\ManyToOne(inversedBy: 'tags')]
    #[ORM\JoinColumn(nullable: false)]
    private ?IdeaBox $tag_box_id = null;

    #[ORM\OneToMany(targetEntity: Idea::class, mappedBy: 'idea_tag_id', orphanRemoval: true)]
    private Collection $ideas;

    public function __construct()
    {
        $this->ideas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTagName(): ?string
    {
        return $this->tag_name;
    }

    public function setTagName(string $tag_name): static
    {
        $this->tag_name = $tag_name;

        return $this;
    }

    public function getTagBoxId(): ?IdeaBox
    {
        return $this->tag_box_id;
    }

    public function setTagBoxId(?IdeaBox $tag_box_id): static
    {
        $this->tag_box_id = $tag_box_id;

        return $this;
    }

    /**
     * @return Collection<int, Idea>
     */
    public function getIdeas(): Collection
    {
        return $this->ideas;
    }

    public function addIdea(Idea $idea): static
    {
        if (!$this->ideas->contains($idea)) {
            $this->ideas->add($idea);
            $idea->setIdeaTagId($this);
        }

        return $this;
    }

    public function removeIdea(Idea $idea): static
    {
        if ($this->ideas->removeElement($idea)) {
            // set the owning side to null (unless already changed)
            if ($idea->getIdeaTagId() === $this) {
                $idea->setIdeaTagId(null);
            }
        }

        return $this;
    }
}

src/Form/IdeaType.php
<?php

namespace App\Form;

use App\Entity\Idea;
use App\Entity\Tag;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class IdeaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('idea_name')
            ->add('idea_tag_id', EntityType::class, [
                'class' => Tag::class,
                'choices' => $options['available_tags'],
                'choice_label' => 'tag_name',
                'placeholder' => "Choisis une catégorie"
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'available_tags' => false,
            'data_class' => Idea::class,
        ]);
    }
}

src/Controller/IdeaController.php
<?php

namespace App\Controller;

use App\Entity\Tag;
use App\Entity\Idea;
use App\Form\IdeaType;
use App\services\BoxManager;
use App\services\IdeaManager;
use App\services\PrintManager;
use App\Repository\IdeaRepository;
use Flasher\Prime\FlasherInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class IdeaController extends AbstractController
{
    private $ideaManager;
    private $printerManager;
    private $flasher;
    private $ideaRepository;

    public function __construct(IdeaManager $ideaManager, PrintManager $printerManager, FlasherInterface $flasher, IdeaRepository $ideaRepository)
    {
        $this->ideaManager = $ideaManager;
        $this->printerManager = $printerManager;
        $this->flasher = $flasher;
        $this->ideaRepository = $ideaRepository;
    }

    
    #[Route('/idea/add', name: 'app_idea_add')]
    #[IsGranted('ROLE_USER')]
    public function ideaAdd(Request $request, BoxManager $boxManager): Response
    {
        $idea = new Idea();
        $allTagInBox = $boxManager->listTagAvailable($this->getUser());

        $ideaForm = $this->createForm(IdeaType::class, $idea, [
            'available_tags' => $allTagInBox,
        ]);
        $ideaForm->handleRequest($request);

        if($ideaForm->isSubmitted())
        {
            $this->ideaManager->addIdea($idea, $this->getUser());

            if($this->getUser()->getIdeaBox()->isIsPrintable() == true && $this->getUser()->getIdeaBox()->isDefaultPrint() == true)
            {
                $this->printerManager->printIdea($idea, $this->getUser()->getIdeaBox()->getPrinterIp());
            }

            $this->flasher->addSuccess('Idée ajoutée avec succés');
            $this->redirectToRoute("app_idea_add");
        }


        
        return $this->render('idea/add.html.twig', [
            'formIdea' => $ideaForm->createView(),
        ]);
    }

    
    #[Route('/idea/list', name: 'app_idea_list')]
    public function ideaList()
    {
        return $this->render('idea/list.html.twig', [
            'ideaInBox' => $this->ideaManager->listIdea($this->getUser())
        ]);
    }

    #[Route('/idea/remove/{id}', name: 'app_idea_remove')]
    #[IsGranted('ROLE_USER')]
    public function ideaRemove(Idea $idea)
    {
        $this->ideaManager->removeIdea($idea);

        $this->flasher->addSuccess('Idée supprimée avec succés');

        return $this->redirectToRoute('app_idea_list');
    }

    
    #[Route('/idea/print/{id}', name: 'app_idea_print')]
    #[IsGranted('ROLE_USER')]
    public function ideaPrint(Idea $idea)
    {
        $this->printerManager->printIdea($idea, $this->getUser()->getIdeaBox()->getPrinterIp());
        
        return $this->redirectToRoute("app_idea_list");
    }

    
    #[Route('/idea/random/{id}', name: 'app_idea_random')]
    #[IsGranted('ROLE_USER')]
    public function randomIdea(Tag $tag): Response
    {
        $listIdea = $this->ideaRepository->findBy(["idea_tag_id" => $tag->getId()]);
        $randomKey = array_rand($listIdea,1);

        return $this->render('idea/random_idea.html.twig', [
            'random_idea' => $listIdea[$randomKey]
        ]);
    }

}

templates/idea/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}J'ai une idée !{% endblock %}

{% block body %}

    {{ form_start(formIdea) }}
        <div class="flex flex-col items-center justify-center mt-96 lg:mt-44 xl:mt-52 2xl:mt-56">
            {{ form_label(formIdea.idea_tag_id, "Sa catégorie", {'label_attr': {'class': 'lg:mt-5 md:mt-24 text-5xl lg:text-xl mb-5 text-[#918EF4]'}}) }}
            {{ form_widget(formIdea.idea_tag_id, {'attr' : {'class' : 'w-3/4 border-solid border-4 border-[#918EF4] text-3xl md:text-base bg-gray-300 rounded-lg p-2 lg:p-1 text-[#81A684]'}}) }}
            {{ form_label(formIdea.idea_name, "L'idée", {'label_attr': {'class': 'lg:mt-5 md:mt-24 text-5xl lg:text-xl mb-5 text-[#918EF4]'}}) }}
            {{ form_widget(formIdea.idea_name, {'attr' : {'class' : 'w-3/4 border-solid border-4 border-[#918EF4] text-3xl md:text-base bg-gray-300 rounded-lg p-2 lg:p-1 text-[#81A684]'}}) }}
            <button class="mt-24 lg:mt-5 relative inline-flex items-center justify-center p-0.5 mb-2 me-2 overflow-hidden rounded-lg group bg-gradient-to-br from-red-200 via-red-300 to-yellow-200 group-hover:from-red-200 group-hover:via-red-300 group-hover:to-yellow-200 dark:text-white dark:hover:text-gray-900 focus:ring-4 focus:outline-none focus:ring-red-100 dark:focus:ring-red-400" type="submit" onclick="getIpPrinter()">

                <span class=" text-white text-6xl lg:text-xl relative p-5 lg:p-2 transition-all ease-in duration-75 bg-[#918EF4] rounded-md group-hover:bg-opacity-0">
                    J'ai une idée !
                </span>
            </button>
        </div>

    {{ form_end(formIdea) }}

{% endblock %}

templates/idea/list.html.twig
{% block body %}
    <div class="flex flex-col w-full text-start">
        {% for idea in ideaInBox %}
            <div class="flex flex-row border-2 bg-white border-[#918EF4] border-solid w-3/4 lg:w-2/4 ms-auto me-auto rounded-xl p-2 mb-3 justify-between">
                <div class="flex flex-col text-[#4C3957]">
                    <h1 class="font-bold text-2xl">{{ idea.ideaTagId.tagName}}</h1>
                    <h3 class="text-xl">{{ idea.ideaName}}</h3>
                </div>
                <div class="flex flex-row mt-auto mb-auto text-2xl me-5">
                    <button  type="button" id="removeIdea_{{ idea.id }}" onclick="removeIdea({{ idea.id }})">
                        <i class="fa-solid fa-trash text-red-600 border-solid border-[#918EF4] border-2 p-3 rounded-xl"></i>
                    </button>
                    {% if app.user.ideaBox.isPrintable %}
                        <button type="button" id="printIdea_{{ idea.id }}" onclick="printIdea({{ idea.id }})" >
                            <i class="fa-solid fa-print text-[#81A684] ms-10 border-solid border-[#918EF4] border-2 p-3 rounded-xl"></i>
                        </button>
                    {% endif %}
                    
                </div>
            
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/idea/print.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <button> Imprimer </button>

    <h1>{{ idea.ideaTagId.tagName }}</h1>
    <p>{{ idea.ideaName }}</p>

{% endblock %}

templates/idea/random_idea.html.twig
{% block body %}
    <div class="mt-1 w-full">
        <hr class="h-px my-3 bg-black border-0 dark:bg-black">
        <div class="flex flex-row justify-between">
            <p class="ms-2 text-lg text-[#4C3957]">{{ random_idea.ideaName}}</p>

            <div class="flex flex-row mt-auto mb-auto text-2xl me-5">
                <button type="button" id="removeIdea_{{ random_idea.id }}" onclick="removeIdea({{ random_idea.id }})">
                    <i class="fa-solid fa-trash text-red-600 border-solid border-[#918EF4] border-2 p-3 rounded-xl"></i>
                </button>
                <button type="button" id="closeRandom" onclick="closeRandomTag({{ random_idea.ideaTagId.id }})">
                    <i class="fa-solid fa-xmark text-[#81A684] ms-10 border-solid border-[#918EF4] border-2 p-3 rounded-xl"></i>
                </button>
            </div>
        
        </div>

    </div>
{% endblock %}